### ISSUE TITLE
Multiple build warnings

### ISSUE THREAD

**Issue by Postremus** [pro-crafting/Jasper-report-maven-plugin#104]
From #102

> If anyone is going to make additional changes to the PR, and if you want to eliminate some warnings during the build, you can also make the following changes:
> - `pom.xml` -> maven-failsafe-plugin -> renamed the `systemProperties` element to `systemPropertyVariables` (I get a deprecation warning on this -- however, if the maven-failsafe-plugin version isn't controlled by the project, could be host environment dependent)
> - change the classes `JasperMojoConfiguration` and `JasperReportCompiler` to be "package protected" instead of "public" (eliminates Javadoc warnings as these classes do not need to be public as far as I can tell).

**Comment by rturner-edjuster** [comment]
@Postremus I'll create a PR for this (unless you are already doing so)

**Comment by Postremus** [comment]
@rturner-edjuster Please do.
