### ISSUE TITLE
Please place maven artifacts into provided scope

### ISSUE THREAD

**Issue by hazendaz** [pro-crafting/Jasper-report-maven-plugin#37]
Hi,

Maven requires all maven provided artifacts from their distribution (ie maven itself) to be listed in provided scope since it provides them.  This reduces junk in m2 repository.

My current notes have that this plugin had maven core and maven plugin api both in compile scope.  They need to be placed into provided.  Could you please do so and get a release out?

You may have to adjust the usage, I use Eclipse which helps see the resolution better.  If you need assistance here I can help.

Thanks.

**Comment by Postremus** [comment]
Thank you for noticing this..
