### ISSUE TITLE
NoClassDefFoundError: org/mozilla/javascript/EvaluatorException

### ISSUE THREAD

**Issue by ben-arce-hdz** [pro-crafting/Jasper-report-maven-plugin#86]
java 11
maven 4
rhino 1.7.14
jasperreports-plugin 3.5.0

getting the following error:
`Failed to execute goal com.pro-crafting.tools:jasperreports-plugin:3.6.1:jasper (default) on project CrovRestaurante: Error while compiling Jasper reports: java.lang.NoClassDefFoundError: org/mozilla/javascript/EvaluatorException: org.mozilla.javascript.EvaluatorException -> [Help 1]`

**Comment by Postremus** [comment]
Hey @ben-arce-hdz 

I just released Version 3.6.2 of this plugin, which includes a fix vor this.
However this also updates to jasper 6.21.3.

If this causes problems for you, there is a workaround available instead of updating - add the missing dependency to your plugin definition.

```
<plugin>
  <groupId>com.pro-crafting.tools</groupId>
  <artifactId>jasperreports-plugin</artifactId>
  <version>3.6.0</version>
  <dependencies>
    <dependency>
      <groupId>org.mozilla</groupId>
      <artifactId>rhino</artifactId>
      <version>1.7.14</version>
    </dependency>
  </dependencies>
</plugin>
```
