### ISSUE TITLE
Update slf4j to version 2

### ISSUE THREAD

**Issue by Postremus** [pro-crafting/Jasper-report-maven-plugin#9]
relates to https://github.com/pro-crafting/Jasper-report-maven-plugin/pull/6

Can slf4j be updated to version 2?
This should have no effect on users of the plugin, since afaik no dependency of maven plugins is leaking onto the user classpath.

Lets test this out.

**Comment by Postremus** [comment]
https://www.slf4j.org/faq.html#changesInVersion200

slf4j 2 would require updating logging frameworks.
We are right now on maven 3.5.2, not sure if we can update anything there.

Is slf4j even needed as explicit dependency?

**Comment by marschall** [comment]
> Is slf4j even needed as explicit dependency?

I don't think so as we do not have dependencies in the plugin source code.
